# Generated by Django 6.0.1 on 2026-02-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='duration_days',
            new_name='duration_months',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_projects',
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('PRO', 'Pro'), ('ENT', 'Enterprise')], default='PRO', max_length=10),
            preserve_default=False,
        ),
    ]
