# Generated by Django 6.0.1 on 2026-02-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_document_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('TASK', 'Task'), ('FEATURE', 'Feature'), ('IMPROVEMENT', 'Improvement')], default='TASK', max_length=20),
        ),
    ]
