# Generated by Django 6.0.1 on 2026-02-09 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('organisations', '0002_organisation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_role',
            field=models.CharField(blank=True, choices=[('PROJECT_LEAD', 'Project Lead'), ('TEAM_LEAD', 'Team Lead'), ('MANAGER', 'Manager'), ('VIEWER', 'Viewer'), ('ASSIGNEE', 'Assignee')], help_text='Sub-role for employees within an organisation', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invited_at',
            field=models.DateTimeField(blank=True, help_text='When this user was invited to the organisation', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_employee',
            field=models.BooleanField(default=True, help_text='Whether this employee is active within their organisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organisations.organisation'),
        ),
        migrations.CreateModel(
            name='EmployeeInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('employee_role', models.CharField(choices=[('PROJECT_LEAD', 'Project Lead'), ('TEAM_LEAD', 'Team Lead'), ('MANAGER', 'Manager'), ('VIEWER', 'Viewer'), ('ASSIGNEE', 'Assignee')], default='ASSIGNEE', max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
