# Generated by Django 6.0.1 on 2026-02-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_employee_role_user_invited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinvitation',
            name='employee_role',
            field=models.CharField(choices=[('ASSIGNEE', 'Assignee')], default='ASSIGNEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_role',
            field=models.CharField(blank=True, choices=[('ASSIGNEE', 'Assignee')], help_text='Sub-role for employees within an organisation', max_length=20, null=True),
        ),
    ]
