# Generated by Django 6.0.1 on 2026-02-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformauditlog',
            name='action',
            field=models.CharField(choices=[('SUB_ACTIVATED', 'Subscription Activated'), ('SUB_CANCELLED', 'Subscription Cancelled'), ('ORG_CREATED', 'Organisation Created'), ('ORG_BLOCKED', 'Organisation Blocked'), ('ORG_ACTIVATED', 'Organisation Activated'), ('TICKET_CLOSED', 'Ticket Closed')], max_length=50),
        ),
    ]
