# Generated by Django 6.0.1 on 2026-02-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_platformauditlog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformauditlog',
            name='ip_address',
        ),
    ]
