# Generated by Django 6.0.1 on 2026-02-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_platformauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformauditlog',
            name='action',
            field=models.CharField(max_length=255),
        ),
    ]
